# This file contains values from Cookiecutter

default_context:
  project_name: "pymarkdown"
  project_description: "Provides utilities to write markdown from python. "
  organization: "None"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "pietrozullo"
  email: "pietro.zullo@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
